In [57]:
import pandas as pd

In [58]:
df = pd.read_csv('sample.csv')

In [59]:
df.head(9)


Sno             Name   Age   Salary        Designation      Mobile
0    1    Shabeeh Abass  20.0  $20,000            manager  9956432321
1    2           anjani  21.0  $30,000  software engineer  9936344113
2    3           deepak  50.0  $60,000  software engineer  9936344113
3    4           mayank  30.0  $70,000   assistant manger  8976543569
4    5  Aishwarya singh   NaN  $80,000            manager  8876543292
5    6      ayush singh  30.0  $90,000      region manger  9987654328
6    7            neetu   NaN  $70,000   assistant manger  8897535637
7    8         prashant  30.0  $80,000          developer  9977553573
8    9     aditya singh  30.0  $56,000          developer  9927363636

In [60]:
df.isnull()

Sno   Name    Age  Salary  Designation  Mobile
0  False  False  False   False        False   False
1  False  False  False   False        False   False
2  False  False  False   False        False   False
3  False  False  False   False        False   False
4  False  False   True   False        False   False
5  False  False  False   False        False   False
6  False  False   True   False        False   False
7  False  False  False   False        False   False
8  False  False  False   False        False   False
9  False  False  False   False        False   False

In [61]:
df.isnull().sum()

Sno            0
Name           0
Age            2
Salary         0
Designation    0
Mobile         0
dtype: int64

In [62]:
df["Name"].value_counts()

Shabeeh Abass      1
anjani             1
deepak             1
mayank             1
Aishwarya singh    1
ayush singh        1
neetu              1
prashant           1
aditya singh       1
ayushi             1
Name: Name, dtype: int64

In [63]:
df.info

<bound method DataFrame.info of    Sno             Name   Age   Salary        Designation      Mobile
0    1    Shabeeh Abass  20.0  $20,000            manager  9956432321
1    2           anjani  21.0  $30,000  software engineer  9936344113
2    3           deepak  50.0  $60,000  software engineer  9936344113
3    4           mayank  30.0  $70,000   assistant manger  8976543569
4    5  Aishwarya singh   NaN  $80,000            manager  8876543292
5    6      ayush singh  30.0  $90,000      region manger  9987654328
6    7            neetu   NaN  $70,000   assistant manger  8897535637
7    8         prashant  30.0  $80,000          developer  9977553573
8    9     aditya singh  30.0  $56,000          developer  9927363636
9   10           ayushi  30.0  $50,000          developer  9956453324>

In [64]:
df

Sno             Name   Age   Salary        Designation      Mobile
0    1    Shabeeh Abass  20.0  $20,000            manager  9956432321
1    2           anjani  21.0  $30,000  software engineer  9936344113
2    3           deepak  50.0  $60,000  software engineer  9936344113
3    4           mayank  30.0  $70,000   assistant manger  8976543569
4    5  Aishwarya singh   NaN  $80,000            manager  8876543292
5    6      ayush singh  30.0  $90,000      region manger  9987654328
6    7            neetu   NaN  $70,000   assistant manger  8897535637
7    8         prashant  30.0  $80,000          developer  9977553573
8    9     aditya singh  30.0  $56,000          developer  9927363636
9   10           ayushi  30.0  $50,000          developer  9956453324

In [65]:
def Salary_clean(salary):
    if isinstance(salary,str):
        salary= salary.strip()
        if '$'in salary:
            salary=salary.replace('$','')
        if ',' in salary:
            salary=salary.replace(',','')
        return int (salary)
    return salary

In [66]:
df['Salary'].apply(Salary_clean)

0    20000
1    30000
2    60000
3    70000
4    80000
5    90000
6    70000
7    80000
8    56000
9    50000
Name: Salary, dtype: int64

In [67]:
# test run
df['Salary'].apply(Salary_clean)

0    20000
1    30000
2    60000
3    70000
4    80000
5    90000
6    70000
7    80000
8    56000
9    50000
Name: Salary, dtype: int64

In [68]:
# Final run
df['Salary'] = df['Salary'].apply(Salary_clean)
df

Sno             Name   Age  Salary        Designation      Mobile
0    1    Shabeeh Abass  20.0   20000            manager  9956432321
1    2           anjani  21.0   30000  software engineer  9936344113
2    3           deepak  50.0   60000  software engineer  9936344113
3    4           mayank  30.0   70000   assistant manger  8976543569
4    5  Aishwarya singh   NaN   80000            manager  8876543292
5    6      ayush singh  30.0   90000      region manger  9987654328
6    7            neetu   NaN   70000   assistant manger  8897535637
7    8         prashant  30.0   80000          developer  9977553573
8    9     aditya singh  30.0   56000          developer  9927363636
9   10           ayushi  30.0   50000          developer  9956453324

In [69]:
# don't do this ever
df.dropna()

Sno           Name   Age  Salary        Designation      Mobile
0    1  Shabeeh Abass  20.0   20000            manager  9956432321
1    2         anjani  21.0   30000  software engineer  9936344113
2    3         deepak  50.0   60000  software engineer  9936344113
3    4         mayank  30.0   70000   assistant manger  8976543569
5    6    ayush singh  30.0   90000      region manger  9987654328
7    8       prashant  30.0   80000          developer  9977553573
8    9   aditya singh  30.0   56000          developer  9927363636
9   10         ayushi  30.0   50000          developer  9956453324

In [70]:
# test run
df.drop(['Mobile','Sno','Name'],axis=1)

Age  Salary        Designation
0  20.0   20000            manager
1  21.0   30000  software engineer
2  50.0   60000  software engineer
3  30.0   70000   assistant manger
4   NaN   80000            manager
5  30.0   90000      region manger
6   NaN   70000   assistant manger
7  30.0   80000          developer
8  30.0   56000          developer
9  30.0   50000          developer

In [71]:
# final run
df.drop(['Mobile','Sno','Name'],axis=1,inplace=True)

In [72]:
df

Age  Salary        Designation
0  20.0   20000            manager
1  21.0   30000  software engineer
2  50.0   60000  software engineer
3  30.0   70000   assistant manger
4   NaN   80000            manager
5  30.0   90000      region manger
6   NaN   70000   assistant manger
7  30.0   80000          developer
8  30.0   56000          developer
9  30.0   50000          developer

scikit-learn


In [73]:
from sklearn.impute import SimpleImputer

In [74]:
imputer=SimpleImputer()

In [75]:
# trail run
cols = ['Age','Salary']
imputer.fit_transform(df[cols])

array([[2.0000e+01, 2.0000e+04],
       [2.1000e+01, 3.0000e+04],
       [5.0000e+01, 6.0000e+04],
       [3.0000e+01, 7.0000e+04],
       [3.0125e+01, 8.0000e+04],
       [3.0000e+01, 9.0000e+04],
       [3.0125e+01, 7.0000e+04],
       [3.0000e+01, 8.0000e+04],
       [3.0000e+01, 5.6000e+04],
       [3.0000e+01, 5.0000e+04]])

In [76]:
#actual run
cols=['Age','Salary']
df[cols]=imputer.fit_transform(df[cols])
df

Age   Salary        Designation
0  20.000  20000.0            manager
1  21.000  30000.0  software engineer
2  50.000  60000.0  software engineer
3  30.000  70000.0   assistant manger
4  30.125  80000.0            manager
5  30.000  90000.0      region manger
6  30.125  70000.0   assistant manger
7  30.000  80000.0          developer
8  30.000  56000.0          developer
9  30.000  50000.0          developer

In [77]:
df

Age   Salary        Designation
0  20.000  20000.0            manager
1  21.000  30000.0  software engineer
2  50.000  60000.0  software engineer
3  30.000  70000.0   assistant manger
4  30.125  80000.0            manager
5  30.000  90000.0      region manger
6  30.125  70000.0   assistant manger
7  30.000  80000.0          developer
8  30.000  56000.0          developer
9  30.000  50000.0          developer

In [78]:
df['Designation'].value_counts()


developer            3
manager              2
software engineer    2
assistant manger     2
region manger        1
Name: Designation, dtype: int64

In [79]:
# trial run
imp2= SimpleImputer(strategy='most_frequent')
imp2.fit_transform(df[['Designation']])

array([['manager'],
       ['software engineer'],
       ['software engineer'],
       ['assistant manger'],
       ['manager'],
       ['region manger'],
       ['assistant manger'],
       ['developer'],
       ['developer'],
       ['developer']], dtype=object)

In [80]:
#actual run
df['Designation']=imp2.fit_transform(df[['Designation']])
df

Age   Salary        Designation
0  20.000  20000.0            manager
1  21.000  30000.0  software engineer
2  50.000  60000.0  software engineer
3  30.000  70000.0   assistant manger
4  30.125  80000.0            manager
5  30.000  90000.0      region manger
6  30.125  70000.0   assistant manger
7  30.000  80000.0          developer
8  30.000  56000.0          developer
9  30.000  50000.0          developer

no missing values


In [81]:
df

Age   Salary        Designation
0  20.000  20000.0            manager
1  21.000  30000.0  software engineer
2  50.000  60000.0  software engineer
3  30.000  70000.0   assistant manger
4  30.125  80000.0            manager
5  30.000  90000.0      region manger
6  30.125  70000.0   assistant manger
7  30.000  80000.0          developer
8  30.000  56000.0          developer
9  30.000  50000.0          developer

In [82]:
df[['Designation']].ndim

2

adding data to existing data frame

In [83]:
gender=['male','female']*5

In [84]:
df['Gender']=gender

Renaming Columns

In [85]:
#rename columns
df.rename({'Salary':'pay'},axis=1,inplace=True)
df

Age      pay        Designation  Gender
0  20.000  20000.0            manager    male
1  21.000  30000.0  software engineer  female
2  50.000  60000.0  software engineer    male
3  30.000  70000.0   assistant manger  female
4  30.125  80000.0            manager    male
5  30.000  90000.0      region manger  female
6  30.125  70000.0   assistant manger    male
7  30.000  80000.0          developer  female
8  30.000  56000.0          developer    male
9  30.000  50000.0          developer  female

In [86]:
df.loc[0]

Age               20.0
pay            20000.0
Designation    manager
Gender            male
Name: 0, dtype: object

In [87]:
row=[{
    'Age':19,
    'pay':934552,
    'Designation':'manager',
    "Gender":'Female'
}]
    

In [88]:
df=df.append(row,ignore_index=True)

In [89]:
df

Age       pay        Designation  Gender
0   20.000   20000.0            manager    male
1   21.000   30000.0  software engineer  female
2   50.000   60000.0  software engineer    male
3   30.000   70000.0   assistant manger  female
4   30.125   80000.0            manager    male
5   30.000   90000.0      region manger  female
6   30.125   70000.0   assistant manger    male
7   30.000   80000.0          developer  female
8   30.000   56000.0          developer    male
9   30.000   50000.0          developer  female
10  19.000  934552.0            manager  Female

In [90]:
df['Gender'].value_counts()

male      5
female    5
Female    1
Name: Gender, dtype: int64

In [91]:
from sklearn.preprocessing import LabelEncoder

In [92]:
gender_enc = LabelEncoder()
gender_enc.fit(df['Gender'])

LabelEncoder()

In [93]:
gender_enc.transform(df['Gender'])

array([2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 0])

In [94]:
df['Gender']=gender_enc.transform(df['Gender'])
df

Age       pay        Designation  Gender
0   20.000   20000.0            manager       2
1   21.000   30000.0  software engineer       1
2   50.000   60000.0  software engineer       2
3   30.000   70000.0   assistant manger       1
4   30.125   80000.0            manager       2
5   30.000   90000.0      region manger       1
6   30.125   70000.0   assistant manger       2
7   30.000   80000.0          developer       1
8   30.000   56000.0          developer       2
9   30.000   50000.0          developer       1
10  19.000  934552.0            manager       0

In [95]:
gender_enc.classes_

array(['Female', 'female', 'male'], dtype=object)

In [96]:
gender_enc.inverse_transform([0,1,1]) #decode

array(['Female', 'female', 'female'], dtype=object)

In [97]:
df.Designation.value_counts()

manager              3
developer            3
software engineer    2
assistant manger     2
region manger        1
Name: Designation, dtype: int64

In [98]:
df.Designation.unique()

array(['manager', 'software engineer', 'assistant manger',
       'region manger', 'developer'], dtype=object)

In [99]:
df.Designation.nunique()

5

In [100]:
df.values

array([[20.0, 20000.0, 'manager', 2],
       [21.0, 30000.0, 'software engineer', 1],
       [50.0, 60000.0, 'software engineer', 2],
       [30.0, 70000.0, 'assistant manger', 1],
       [30.125, 80000.0, 'manager', 2],
       [30.0, 90000.0, 'region manger', 1],
       [30.125, 70000.0, 'assistant manger', 2],
       [30.0, 80000.0, 'developer', 1],
       [30.0, 56000.0, 'developer', 2],
       [30.0, 50000.0, 'developer', 1],
       [19.0, 934552.0, 'manager', 0]], dtype=object)

In [101]:
from sklearn.preprocessing import OneHotEncoder


In [102]:
desig_enc = OneHotEncoder()
desig_enc.fit(df[['Designation']])



OneHotEncoder()

In [103]:
df

Age       pay        Designation  Gender
0   20.000   20000.0            manager       2
1   21.000   30000.0  software engineer       1
2   50.000   60000.0  software engineer       2
3   30.000   70000.0   assistant manger       1
4   30.125   80000.0            manager       2
5   30.000   90000.0      region manger       1
6   30.125   70000.0   assistant manger       2
7   30.000   80000.0          developer       1
8   30.000   56000.0          developer       2
9   30.000   50000.0          developer       1
10  19.000  934552.0            manager       0

In [104]:
Designation_dummies = desig_enc.transform(df[['Designation']]).toarray()
Designation_dummies


array([[0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.]])

In [105]:
df.drop(columns=['Designation'],axis=1,inplace=True)

In [106]:
import numpy as np

In [107]:
data = np.hstack((Designation_dummies,df.values))
data.shape


(11, 8)

In [108]:
# option 2(better version)
desig_dummy_df=pd.DataFrame(Designation_dummies)
desig_dummy_df

0    1    2    3    4
0   0.0  0.0  1.0  0.0  0.0
1   0.0  0.0  0.0  0.0  1.0
2   0.0  0.0  0.0  0.0  1.0
3   1.0  0.0  0.0  0.0  0.0
4   0.0  0.0  1.0  0.0  0.0
5   0.0  0.0  0.0  1.0  0.0
6   1.0  0.0  0.0  0.0  0.0
7   0.0  1.0  0.0  0.0  0.0
8   0.0  1.0  0.0  0.0  0.0
9   0.0  1.0  0.0  0.0  0.0
10  0.0  0.0  1.0  0.0  0.0

In [109]:
data_df = pd.concat([desig_dummy_df,df],axis=1)

In [110]:
from sklearn.preprocessing import StandardScaler,MinMaxScaler

In [111]:
mxScalar = MinMaxScaler()
mxScalar.fit(data_df)
scaled_data=mxScalar.transform(data_df)
print(scaled_data)


[[0.         0.         1.         0.         0.         0.03225806
  0.         1.        ]
 [0.         0.         0.         0.         1.         0.06451613
  0.01093432 0.5       ]
 [0.         0.         0.         0.         1.         1.
  0.04373726 1.        ]
 [1.         0.         0.         0.         0.         0.35483871
  0.05467158 0.5       ]
 [0.         0.         1.         0.         0.         0.35887097
  0.06560589 1.        ]
 [0.         0.         0.         1.         0.         0.35483871
  0.07654021 0.5       ]
 [1.         0.         0.         0.         0.         0.35887097
  0.05467158 1.        ]
 [0.         1.         0.         0.         0.         0.35483871
  0.06560589 0.5       ]
 [0.         1.         0.         0.         0.         0.35483871
  0.03936354 1.        ]
 [0.         1.         0.         0.         0.         0.35483871
  0.03280295 0.5       ]
 [0.         0.         1.         0.         0.         0.
  1.         0.   

C:\Users\varun\AppData\Local\Programs\Python\Python39\lib\site-packages\sklearn\utils\validation.py:1688: FutureWarning: Feature names only support names that are all strings. Got feature names with dtypes: ['int', 'str']. An error will be raised in 1.2.
  warnings.warn(
C:\Users\varun\AppData\Local\Programs\Python\Python39\lib\site-packages\sklearn\utils\validation.py:1688: FutureWarning: Feature names only support names that are all strings. Got feature names with dtypes: ['int', 'str']. An error will be raised in 1.2.
  warnings.warn(


In [112]:
# this is used in Coding
stdScalar = StandardScaler()
mxScalar.fit(data_df)
scaled_data=mxScalar.transform(data_df)
print(scaled_data)

[[0.         0.         1.         0.         0.         0.03225806
  0.         1.        ]
 [0.         0.         0.         0.         1.         0.06451613
  0.01093432 0.5       ]
 [0.         0.         0.         0.         1.         1.
  0.04373726 1.        ]
 [1.         0.         0.         0.         0.         0.35483871
  0.05467158 0.5       ]
 [0.         0.         1.         0.         0.         0.35887097
  0.06560589 1.        ]
 [0.         0.         0.         1.         0.         0.35483871
  0.07654021 0.5       ]
 [1.         0.         0.         0.         0.         0.35887097
  0.05467158 1.        ]
 [0.         1.         0.         0.         0.         0.35483871
  0.06560589 0.5       ]
 [0.         1.         0.         0.         0.         0.35483871
  0.03936354 1.        ]
 [0.         1.         0.         0.         0.         0.35483871
  0.03280295 0.5       ]
 [0.         0.         1.         0.         0.         0.
  1.         0.   

C:\Users\varun\AppData\Local\Programs\Python\Python39\lib\site-packages\sklearn\utils\validation.py:1688: FutureWarning: Feature names only support names that are all strings. Got feature names with dtypes: ['int', 'str']. An error will be raised in 1.2.
  warnings.warn(
C:\Users\varun\AppData\Local\Programs\Python\Python39\lib\site-packages\sklearn\utils\validation.py:1688: FutureWarning: Feature names only support names that are all strings. Got feature names with dtypes: ['int', 'str']. An error will be raised in 1.2.
  warnings.warn(
